use crate::{
    algo::{AlgoDigest, AlgoDigestHasher, AlgoDigestHmac},
    crypto::{cp_hash, hmac_computation, rp_hash, session_key},
};
use tpm2_rs_base::{
    commands::TpmCommand, constants::TpmHandle, Tpm2bAuth, Tpm2bData, Tpm2bDigest, Tpm2bNonce,
    Tpm2bSimple, TpmaSession, TpmiShAuthSession, TpmsAuthCommand, TpmsAuthResponse,
};
use tpm2_rs_errors::{TssResult, TssTcsError};

/// Trait for types representing TPM sessions.
pub trait Session {
    /// Computes the authorization HMAC for this session.
    fn get_auth_command<CmdT: TpmCommand>(
        &mut self,
        cmd: &CmdT,
        cmd_handles: &CmdT::Handles,
        buf: &mut [u8],
    ) -> TssResult<TpmsAuthCommand>;
    /// Validates the authorization response for this session.
    fn validate_auth_response<CmdT: TpmCommand>(
        &mut self,
        resp: &CmdT::RespT,
        resp_handles: &CmdT::RespHandles,
        auth: &TpmsAuthResponse,
        buf: &mut [u8],
    ) -> TssResult<()>;
}

pub struct PasswordSession {
    auth: Tpm2bAuth,
    session_attributes: TpmaSession,
}

impl PasswordSession {
    pub fn new(auth: Tpm2bAuth, session_attributes: TpmaSession) -> Self {
        PasswordSession {
            auth,
            session_attributes,
        }
    }
}

impl Session for PasswordSession {
    fn get_auth_command<CmdT: TpmCommand>(
        &mut self,
        _cmd: &CmdT,
        _cmd_handles: &CmdT::Handles,
        _buf: &mut [u8],
    ) -> TssResult<TpmsAuthCommand> {
        Ok(TpmsAuthCommand {
            session_handle: TpmiShAuthSession::RS_PW,
            nonce: Tpm2bNonce::default(),
            session_attributes: self.session_attributes,
            hmac: self.auth,
        })
    }
    fn validate_auth_response<CmdT: TpmCommand>(
        &mut self,
        _resp: &CmdT::RespT,
        _resp_handles: &CmdT::RespHandles,
        auth: &TpmsAuthResponse,
        _buf: &mut [u8],
    ) -> TssResult<()> {
        if auth.nonce.get_size() != 0
            || auth.session_attributes != self.session_attributes
            || auth.hmac.get_size() != 0
        {
            Err(TssTcsError::BadParameter.into())
        } else {
            Ok(())
        }
    }
}

// A simple Hmac session.
pub struct HmacSession<D>
where
    D: AlgoDigest,
{
    auth_val: Vec<u8>,
    /// The session handle returned by the `TPM2_StartAuthSession` command.
    session_handle: TpmiShAuthSession,
    /// The attributes used for this session.
    session_attributes: TpmaSession,
    /// The optional session key to be used for the HMAC. Required if
    /// `TPM2_StartAuthSession` was called with a the session handle `bind` set
    /// to a non-`TPM_RH_NULL` value.
    session_key: Option<<D::Hmac as AlgoDigestHmac>::Output>,
    /// The random nonce generated by this HMAC session structure. This is
    /// updated on each command and part of the HMAC computation.
    nonce_caller: Tpm2bNonce,
    /// The (random) nonce returned by the TPM. This is updated on each response
    /// and part of the HMAC computation.
    nonce_tpm: Tpm2bNonce,
}

impl<D> HmacSession<D>
where
    D: AlgoDigest,
{
    pub fn new(
        auth_val: Vec<u8>,
        session_handle: TpmiShAuthSession,
        session_attributes: TpmaSession,
        session_key: Option<<D::Hmac as AlgoDigestHmac>::Output>,
        nonce_tpm: Tpm2bNonce,
    ) -> Self {
        Self {
            auth_val,
            session_handle,
            session_attributes,
            session_key,
            // Init empty value; will be randomly generated and updated on each
            // command.
            nonce_caller: Tpm2bNonce::default(),
            nonce_tpm,
        }
    }
}

/// Spec (Part 1): 17.6 Session-Based Authorizations
impl<D> Session for HmacSession<D>
where
    D: AlgoDigest,
{
    fn get_auth_command<CmdT: TpmCommand>(
        &mut self,
        cmd: &CmdT,
        cmd_handles: &CmdT::Handles,
        buf: &mut [u8],
    ) -> TssResult<TpmsAuthCommand> {
        // > The minimum size for nonceCaller in TPM2_StartAuthSession() is 16
        // > octets. The maximum size that may be requested for nonceTPM is the
        // > size of the digest produced by the authorization session hash.
        // > Example: For SHA-1, the maximum size for nonceTPM is 20 octets and
        // > for SHA256 it is 32 octets.

        // We generally assume that the nonce size is 64-bytes or less. If the
        // hasher output is larger than that, we just cut it off at 64-bytes.
        buf[..64].copy_from_slice(&rand::random::<[u8; 64]>());
        let cut_off = D::Hasher::OUTPUT_SIZE.min(64);
        self.nonce_caller = Tpm2bDigest::from_bytes(&buf[..cut_off])?;

        // Retrieve the session key if available, compute the command+handles
        // hash, and then the corresponding HMAC - to be validated by the TPM.
        let session_key = self.session_key.as_ref().map(|k| k.as_ref()).unwrap_or(&[]);
        let cp_hash = cp_hash::<CmdT, D::Hasher>(cmd, cmd_handles, buf)?;

        let computed_hmac = hmac_computation::<D::Hmac>(
            &self.auth_val,
            &session_key,
            cp_hash.as_ref(),
            // Our newly generated TPM is the newer.
            &self.nonce_caller,
            // The nonce returned by the TPM is older.
            &self.nonce_tpm,
            &self.session_attributes,
            buf,
        )?;

        let cmd = TpmsAuthCommand {
            session_handle: self.session_handle,
            nonce: self.nonce_caller,
            session_attributes: self.session_attributes,
            hmac: computed_hmac,
        };

        Ok(cmd)
    }
    fn validate_auth_response<CmdT: TpmCommand>(
        &mut self,
        resp: &CmdT::RespT,
        // TODO: Do something with that? Validate it?
        resp_handles: &CmdT::RespHandles,
        auth: &TpmsAuthResponse,
        buf: &mut [u8],
    ) -> TssResult<()> {
        if auth.nonce.get_size() as usize != D::Hasher::OUTPUT_SIZE.min(64)
            || auth.session_attributes != self.session_attributes
            || auth.hmac.get_size() as usize != D::Hmac::OUTPUT_SIZE
        {
            return Err(TssTcsError::BadParameter.into());
        }

        // Retrieve session key if available, compute the response hash, and
        // then the corresponding HMAC - which is then matched against the
        // returned HMAC from the TPM.
        let session_key = self.session_key.as_ref().map(|k| k.as_ref()).unwrap_or(&[]);
        let rp_hash = rp_hash::<CmdT, D::Hasher>(resp, buf)?;

        let computed_hmac = hmac_computation::<D::Hmac>(
            &self.auth_val,
            &session_key,
            rp_hash.as_ref(),
            // The newly returned nonce by the TPM is newer.
            &auth.nonce,
            // Our generated nonce on the command call is older.
            &self.nonce_caller,
            &self.session_attributes,
            buf,
        )?;

        if computed_hmac.get_buffer() != auth.hmac.get_buffer() {
            // TODO: Change error variant?
            return Err(TssTcsError::BadParameter.into());
        }

        // Update the TPM's nonce, which MUST be used on the next authorized
        // command.
        self.nonce_tpm = auth.nonce;

        Ok(())
    }
}
